name: "Github Release"
author: "Eager Minds"
branding:
  icon: "package"
  color: "green"
description: "Generate GitHub release for a tag"

inputs:
  tag_name:
    description: "The tag name"
    required: true
  release_name:
    description: "The name of the release to publish"
    required: true
  changelog_path:
    description: "Changelog file path to get release description"
    required: false
outputs:
  release_url:
    description: "Created release URL"
    value: ${{ steps.release.outputs.release_url }}


runs:
  using: 'composite'
  steps:
    - id: get_changelog_message
      run: |
        changelog_message=$($GITHUB_ACTION_PATH/generate-changelog.sh)
        echo "changelog_message=$changelog_message" >> $GITHUB_OUTPUT
      shell: bash
      env:
        TAG_NAME: ${{ inputs.tag_name }}
        CHANGELOG_PATH: ${{ inputs.changelog_path }}
    - id: release
      name: Release
      run: echo "release_url="$(gh release create "$TAG_NAME" -t "$RELEASE_NAME" --notes "${TAG_MESSAGE}") >> $GITHUB_OUTPUT
      shell: bash
      env:
        TAG_NAME: "${{ inputs.tag_name }}"
        RELEASE_NAME: "${{ inputs.release_name }}"
        TAG_MESSAGE: "${{ steps.get_changelog_message.outputs.changelog_message }}"
