name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CI_COMMIT_AUTHOR: Continuous Integration
  CI_COMMIT_EMAIL: continuous_integration@noreply.eagerminds.tech
  CHANGELOG_PATH: CHANGELOG

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git config
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"

      - id: release
        uses: eager-minds/github-actions-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          changelog_path: ${{ env.CHANGELOG_PATH }}

      - id: echo_release_output
        name: Echo Release Output
        run: echo ${{ steps.release.outputs.release_url }}

      - name: Control release failure
        if: ${{ failure() }}
        run: echo "Previous step failed"
